# Generated by Django 5.1.4 on 2026-02-20 16:15

import django.db.models.deletion
import mptt.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('intitule', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Classe de compte',
                'verbose_name_plural': 'Classes de comptes',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=20)),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('regime_fiscal', models.CharField(blank=True, max_length=100)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rccm', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=200)),
                ('nature', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], default='debit', max_length=10)),
                ('type_compte', models.CharField(choices=[('detail', 'Détail'), ('collectif', 'Collectif')], default='detail', max_length=20)),
                ('lettrable', models.BooleanField(default=False)),
                ('est_tiers', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='comptabilite.classecompte')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_comptes', to='comptabilite.compte')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='comptabilite.societe')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['numero'],
                'unique_together': {('societe', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=200)),
                ('type_journal', models.CharField(choices=[('achat', 'Achats'), ('vente', 'Ventes'), ('banque', 'Banque'), ('caisse', 'Caisse'), ('od', 'Opérations Diverses'), ('an', 'À Nouveau')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('compte_contrepartie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_contrepartie', to='comptabilite.compte')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='comptabilite.societe')),
            ],
            options={
                'verbose_name': 'Journal comptable',
                'verbose_name_plural': 'Journaux comptables',
                'ordering': ['code'],
                'unique_together': {('societe', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ModeleEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_ecritures', to='comptabilite.journalcomptable')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_ecritures', to='comptabilite.societe')),
            ],
            options={
                'verbose_name': "Modèle d'écriture",
                'verbose_name_plural': "Modèles d'écriture",
                'ordering': ['code'],
                'unique_together': {('societe', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LigneModeleEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('ordre', models.IntegerField(default=0)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_modeles', to='comptabilite.compte')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.modeleecriture')),
            ],
            options={
                'verbose_name': "Ligne de modèle d'écriture",
                'verbose_name_plural': "Lignes de modèles d'écriture",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piece', models.CharField(max_length=20)),
                ('date_piece', models.DateField()),
                ('libelle', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('brouillard', 'Brouillard'), ('valide', 'Validé')], default='brouillard', max_length=20)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='comptabilite.exercicecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='comptabilite.journalcomptable')),
            ],
            options={
                'verbose_name': 'Pièce comptable',
                'verbose_name_plural': 'Pièces comptables',
                'ordering': ['journal', 'numero_piece'],
                'unique_together': {('exercice', 'journal', 'numero_piece')},
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('lettrage_code', models.CharField(blank=True, default='', max_length=10)),
                ('ordre', models.IntegerField(default=0)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_ecriture', to='comptabilite.compte')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.piececomptable')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('solde_final', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('nb_rapproches', models.IntegerField(default=0)),
                ('nb_non_rapproches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte_banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_bancaires', to='comptabilite.compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_bancaires', to='comptabilite.exercicecomptable')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_bancaires', to='comptabilite.societe')),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('libelle', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('non_rapproche', 'Non rapproché'), ('rapproche', 'Rapproché'), ('ignore', 'Ignoré')], default='non_rapproche', max_length=20)),
                ('ligne_ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_releve', to='comptabilite.ligneecriture')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.relevebancaire')),
            ],
            options={
                'verbose_name': 'Ligne de relevé',
                'verbose_name_plural': 'Lignes de relevé',
                'ordering': ['date_operation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_acquisition', models.DateField()),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_amortissement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duree_amortissement', models.IntegerField(help_text='Durée en années')),
                ('methode_amortissement', models.CharField(choices=[('lineaire', 'Linéaire'), ('degressif', 'Dégressif')], default='lineaire', max_length=20)),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='comptabilite.compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='comptabilite.exercicecomptable')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='comptabilite.societe')),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'ordering': ['designation'],
            },
        ),
        migrations.AddField(
            model_name='exercicecomptable',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='comptabilite.societe'),
        ),
        migrations.AddField(
            model_name='classecompte',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_comptes', to='comptabilite.societe'),
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('type_tiers', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('compte_collectif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers_associes', to='comptabilite.compte')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='comptabilite.societe')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['nom'],
                'unique_together': {('societe', 'code')},
            },
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecriture', to='comptabilite.tiers'),
        ),
        migrations.AlterUniqueTogether(
            name='exercicecomptable',
            unique_together={('societe', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classecompte',
            unique_together={('societe', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='ligneecriture',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='ligne_no_debit_and_credit'),
        ),
        migrations.AddConstraint(
            model_name='ligneecriture',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ligne_no_negative_amounts'),
        ),
    ]
