# Generated by Django 5.1.4 on 2026-02-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='nif',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIF'),
        ),
    ]
