# Generated by Django 5.1.4 on 2026-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_societe_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='forme_juridique',
            field=models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('SNC', 'SNC'), ('EI', 'Entreprise individuelle'), ('GIE', 'GIE'), ('ONG', 'ONG'), ('AUTRE', 'Autre')], default='', max_length=10),
        ),
    ]
